aicp_m7-userdebug lp5.0
aicp_endeavoru-userdebug lp5.0
aicp_grouper-userdebug lp5.0
aicp_hammerhead-userdebug lp5.0
aicp_deb-userdebug lp5.0
aicp_flo-userdebug lp5.0
aicp_mako-userdebug lp5.0
aicp_tilapia-userdebug lp5.0
aicp_m7vzw-userdebug lp5.0
aicp_e980-userdebug lp5.0
